# Updating F1 CSV file

This notebook is for updatinf the original csv file which is used to store historical race data from previous formula 1 races. After each race we will need to update the CSV file with 22 new rows for each driver in the 2026 season

Previewing the CSV file and loading it into the notebook

In [ ]:
import pandas as pd # import pandas

# load the csv file into the notebook
f1_data = pd.read_csv("f1_race_driver_rows.csv")

# preview the current last race in the df
f1_data.tail()


# as we can see below the most recent race in the df is from the 2025 Abu Dhabi
# Grand Prix. by the end of this notebook we will aim to have the last race in the
# df being the 2026 Austrailian Grand Prix.

,season,round,race_name,driver,team,grid_position,quali_position,finish_position,status,points,is_winner
3619,2026,3,Japanese Grand Prix,PIA,McLaren,3,3.0,2,Finished,18.0,0
3620,2026,3,Japanese Grand Prix,RUS,Mercedes,2,2.0,4,Finished,12.0,0
3621,2026,3,Japanese Grand Prix,SAI,Williams,16,16.0,15,Finished,0.0,0
3622,2026,3,Japanese Grand Prix,STR,Aston Martin,22,22.0,21,DNF,0.0,0
3623,2026,3,Japanese Grand Prix,VER,Red Bull,11,11.0,8,Finished,4.0,0

In [ ]:
f1_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3624 entries, 0 to 3623
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   season           3624 non-null   int64
 1   round            3624 non-null   int64
 2   race_name        3624 non-null   object
 3   driver           3624 non-null   object
 4   team             3624 non-null   object
 5   grid_position    3624 non-null   int64
 6   quali_position   3620 non-null   float64
 7   finish_position  3624 non-null   int64
 8   status           3624 non-null   object
 9   points           3624 non-null   float64
 10  is_winner        3624 non-null   int64
dtypes: float64(2), int64(5), object(4)
memory usage: 311.6+ KB

In [ ]:
new_race = pd.DataFrame([
    # George Russell
    {"season":2026, "round":3, "race_name":"Japanese Grand Prix", "driver":"RUS", "team":"Mercedes", "grid_position":2, "quali_position": 2, "finish_position": 4, "status":"Finished", "points":12, "is_winner":0},

    # Kimi Antonelli
    {"season":2026, "round":3, "race_name":"Japanese Grand Prix", "driver":"ANT", "team":"Mercedes", "grid_position":1, "quali_position": 1, "finish_position": 1, "status":"Finished", "points":25, "is_winner":1},

    # charles leclerc
    {"season":2026, "round":3, "race_name":"Japanese Grand Prix", "driver":"LEC", "team":"Ferarri", "grid_position":4, "quali_position":4, "finish_position":3, "status":"Finished", "points":15, "is_winner":0},

    # lewis hamilton
    {"season":2026, "round":3, "race_name":"Japanese Grand Prix", "driver":"HAM", "team":"Ferarri", "grid_position":6, "quali_position":6, "finish_position": 6, "status":"Finished", "points":8, "is_winner":0},

    # lando norris
    {"season":2026, "round":3, "race_name":"Japanese Grand Prix", "driver":"NOR", "team":"McLaren", "grid_position":5, "quali_position":5, "finish_position":5, "status":"DNF", "points": 10, "is_winner":0},

    # max verstappen
    {"season":2026, "round":3, "race_name":"Japanese Grand Prix", "driver":"VER", "team":"Red Bull", "grid_position": 11, "quali_position": 11, "finish_position": 8, "status": "Finished", "points": 4, "is_winner":0},

    # oliver bearnman
    {"season":2026, "round":3, "race_name":"Japanese Grand Prix", "driver":"BEA", "team":"Haas", "grid_position":18, "quali_position":18, "finish_position":22, "status":"DNF", "points":0, "is_winner":0},

    # arved linblad
    {"season":2026, "round":3, "race_name":"Japanese Grand Prix", "driver":"LIN", "team":"Racing Bulls", "grid_position":10, "quali_position":10, "finish_position":14, "status":"Finished", "points":0, "is_winner":0},

    # gabrielle bortoleto
    {"season":2026, "round":3, "race_name":"Japanese Grand Prix", "driver":"BOR", "team":"Audi", "grid_position":9, "quali_position":9, "finish_position":13, "status":"Finished", "points":0, "is_winner":0},

    # piere gasly
    {"season":2026, "round":3, "race_name":"Japanese Grand Prix", "driver":"GAS", "team":"Alpine", "grid_position": 7, "quali_position": 7, "finish_position": 7, "status":"Finished", "points": 6, "is_winner":0},

    # estaban ocon
    {"season":2026, "round":3, "race_name":"Japanese Grand Prix", "driver":"OCO", "team":"Haas", "grid_position": 12, "quali_position": 12, "finish_position":10, "status":"Finished", "points": 1, "is_winner":0},

    # alex albon
    {"season":2026, "round":3, "race_name":"Japanese Grand Prix", "driver":"ALB", "team":"Williams", "grid_position": 17, "quali_position": 17, "finish_position":20, "status":"Finished", "points":0, "is_winner":0},

    # liam lawson
    {"season":2026, "round":3, "race_name":"Japanese Grand Prix", "driver":"LAW", "team":"Racing Bulls", "grid_position": 14, "quali_position":14, "finish_position":9, "status":"Finished", "points":2, "is_winner":0},

    # franco colapento
    {"season":2026, "round":3, "race_name":"Japanese Grand Prix", "driver":"COL", "team":"Alpine", "grid_position": 15, "quali_position": 15, "finish_position":16, "status":"Finished", "points":0, "is_winner":0},

    # carlos sains
    {"season":2026, "round":3, "race_name":"Japanese Grand Prix", "driver":"SAI", "team":"Williams", "grid_position": 16, "quali_position": 16, "finish_position": 15, "status":"Finished", "points": 0, "is_winner": 0},

    # sergio pereze
    {"season":2026, "round":3, "race_name":"Japanese Grand Prix", "driver":"PER", "team":"Cadillac", "grid_position":19, "quali_position":19, "finish_position":17, "status":"Finished", "points":0, "is_winner":0},

    # lance stroll
    {"season":2026, "round":3, "race_name":"Japanese Grand Prix", "driver":"STR", "team":"Aston Martin", "grid_position":22, "quali_position":22, "finish_position":21, "status":"DNF", "points":0, "is_winner":0},

    # fernando alonzo
    {"season":2026, "round":3, "race_name":"Japanese Grand Prix", "driver":"ALO", "team":"Aston Martin", "grid_position":21, "quali_position":21, "finish_position":18, "status":"Finished", "points":0, "is_winner":0},

    # valtteri bottas
    {"season":2026, "round":3, "race_name":"Japanese Grand Prix", "driver":"BOT", "team":"Cadillac", "grid_position":20, "quali_position":20, "finish_position":19, "status":"Finished", "points":0, "is_winner":0},

    # isack hadjar
    {"season":2026, "round":3, "race_name":"Japanese Grand Prix", "driver":"HAD", "team":"Red Bull", "grid_position":8, "quali_position":8, "finish_position":12, "status":"Finished", "points":0, "is_winner":0},

    # oscar piastri
    {"season":2026, "round":3, "race_name":"Japanese Grand Prix", "driver":"PIA", "team":"McLaren", "grid_position":3, "quali_position":3, "finish_position":2, "status":"Finished", "points":18, "is_winner":0},

    # niko hulkenburgh
    {"season":2026, "round":3, "race_name":"Japanese Grand Prix", "driver":"HUL", "team":"Audi", "grid_position":13, "quali_position":13, "finish_position":11, "status":"Finished", "points":0, "is_winner":0}
])

duplicate_check = f1_data.merge(
    new_race[["season", "round", "driver"]],
    on=["season", "round", "driver"],
    how="inner"
)

if not duplicate_check.empty:
    print("Some rows for this race already exist in the master CSV.")
    display(duplicate_check)
else:
    # Append new race
    df = pd.concat([f1_data, new_race], ignore_index=True)

    # Keep rows ordered neatly
    df = df.sort_values(["season", "round", "driver"]).reset_index(drop=True)

    # Save updated file
    df.to_csv("/content/f1_race_driver_rows.csv", index=False)

    # Update f1_data to reflect the changes
    f1_data = df.copy()

    print("Race added successfully.")
    print("New dataset shape:", f1_data.shape)

Race added successfully.
New dataset shape: (3624, 11)

here we are checking to make sure the new rows were saved to the CSV file correctly.

In [ ]:
f1_data[(f1_data["season"] == 2026) & (f1_data["round"] == 3)]

,season,round,race_name,driver,team,grid_position,quali_position,finish_position,status,points,is_winner
3602,2026,3,Japanese Grand Prix,ALB,Williams,17,17.0,20,Finished,0.0,0
3603,2026,3,Japanese Grand Prix,ALO,Aston Martin,21,21.0,18,Finished,0.0,0
3604,2026,3,Japanese Grand Prix,ANT,Mercedes,1,1.0,1,Finished,25.0,1
3605,2026,3,Japanese Grand Prix,BEA,Haas,18,18.0,22,DNF,0.0,0
3606,2026,3,Japanese Grand Prix,BOR,Audi,9,9.0,13,Finished,0.0,0
3607,2026,3,Japanese Grand Prix,BOT,Cadillac,20,20.0,19,Finished,0.0,0
3608,2026,3,Japanese Grand Prix,COL,Alpine,15,15.0,16,Finished,0.0,0
3609,2026,3,Japanese Grand Prix,GAS,Alpine,7,7.0,7,Finished,6.0,0
3610,2026,3,Japanese Grand Prix,HAD,Red Bull,8,8.0,12,Finished,0.0,0
3611,2026,3,Japanese Grand Prix,HAM,Ferarri,6,6.0,6,Finished,8.0,0
3612,2026,3,Japanese Grand Prix,HUL,Audi,13,13.0,11,Finished,0.0,0
3613,2026,3,Japanese Grand Prix,LAW,Racing Bulls,14,14.0,9,Finished,2.0,0
3614,2026,3,Japanese Grand Prix,LEC,Ferarri,4,4.0,3,Finished,15.0,0
3615,2026,3,Japanese Grand Prix,LIN,Racing Bulls,10,10.0,14,Finished,0.0,0
3616,2026,3,Japanese Grand Prix,NOR,McLaren,5,5.0,5,DNF,10.0,0
3617,2026,3,Japanese Grand Prix,OCO,Haas,12,12.0,10,Finished,1.0,0
3618,2026,3,Japanese Grand Prix,PER,Cadillac,19,19.0,17,Finished,0.0,0
3619,2026,3,Japanese Grand Prix,PIA,McLaren,3,3.0,2,Finished,18.0,0
3620,2026,3,Japanese Grand Prix,RUS,Mercedes,2,2.0,4,Finished,12.0,0
3621,2026,3,Japanese Grand Prix,SAI,Williams,16,16.0,15,Finished,0.0,0
3622,2026,3,Japanese Grand Prix,STR,Aston Martin,22,22.0,21,DNF,0.0,0
3623,2026,3,Japanese Grand Prix,VER,Red Bull,11,11.0,8,Finished,4.0,0

In [ ]:
f1_data.tail()

,season,round,race_name,driver,team,grid_position,quali_position,finish_position,status,points,is_winner
3619,2026,3,Japanese Grand Prix,PIA,McLaren,3,3.0,2,Finished,18.0,0
3620,2026,3,Japanese Grand Prix,RUS,Mercedes,2,2.0,4,Finished,12.0,0
3621,2026,3,Japanese Grand Prix,SAI,Williams,16,16.0,15,Finished,0.0,0
3622,2026,3,Japanese Grand Prix,STR,Aston Martin,22,22.0,21,DNF,0.0,0
3623,2026,3,Japanese Grand Prix,VER,Red Bull,11,11.0,8,Finished,4.0,0